### ISSUE TITLE
ffmpeg

### ISSUE THREAD

**Issue by rheinon** [flor0/nextcloud-docker#3]
How do I add ffmpeg to the script?

**Comment by flor0** [comment]
Go to `php-fpm/Dockerfile`. Find this line `RUN apt-get update && apt-get install -y \` and add this below it: `ffpmeg \`.
Keep in mind preview generation is [not available yet](https://github.com/mlocati/docker-php-extension-installer/pull/811) for php8.3, which is the recommended php version for nextcloud.
