### ISSUE TITLE
NC V 29.0.0 isues with We have detected multiple invalid login attempts from your IP...

### ISSUE THREAD

**Issue by rickgitdone** [flor0/nextcloud-docker#7]
Now running v 28.0.5. Can logon using localhost only.

I have set the trusted domain section in config.php. Any URL rewrites to https are invalid as I have no SSL certs for this installation. Do you have any plans to provide for SSL configurations while using nginx and docker?

**Comment by flor0** [comment]
I _highly_ recommend using traefik if you use this project. You can check out the traefik branch. It will handle SSL certificates for you.
If you _must_ use nginx by itself I recommend certbot. [Here's](https://eff-certbot.readthedocs.io/en/stable/install.html#alternative-1-docker) a link to the docs on how to set it up with docker.
