### ISSUE TITLE
Error when building at imagick install

### ISSUE THREAD

**Issue by brunobeeee** [flor0/nextcloud-docker#8]
I can see that you uncommented the imagegick on your last commit to the Dockerfile. Is this working for you? I still sometimes get an error when building this image.

On the imagick repo [the issue](https://github.com/Imagick/imagick/issues/640#issuecomment-2034088994) is still open. Also there are more people complaining about it [failing sometimes](https://github.com/StephenMiracle/frankenwp/issues/5#issue-2279204297).
Imo this is the [best fix](https://github.com/Imagick/imagick/issues/640#issuecomment-2077206945) for now bc it allows you to still use PHP 8.3:
```
RUN install-php-extensions imagick/imagick@master
```

PS: I really appreciate your work! I also hate the AIO install of Nextcloud and this is the perfect setup imo.

**Comment by flor0** [comment]
I hear you. Will fix this today. Also thanks for your kind words. I'm glad this project is useful for someone!
