### ISSUE TITLE
Warnings in nginx.conf

### ISSUE THREAD

**Issue by jsaddiction** [flor0/nextcloud-docker#9]
Disclaimer:
I am not an nginx guru.

The following warnings are present concerning the nginx.conf file:

`[warn] duplicate extension "js", content type: "text/javascript", previous content type: "application/javascript" in /etc/nginx/nginx.conf:75`

`[warn] duplicate extension "wasm", content type: "application/wasm", previous content type: "application/wasm" in /etc/nginx/nginx.conf:76`

It seems the entries listed are needed but I'm not sure why nginx disagrees.

**Comment by flor0** [comment]
I get this too. This is probably because it overrides the defaults of nginx somehwere. Should be fine since that's the nginx.conf provided by the official nextcloud docs.
